# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  publish_scheduled_library_editorials:
    class: DailyEditorialPublicationCoordinatorJob
    queue: maintenance
    schedule: every 15 minutes
  schedule_night_notifications:
    class: NightNotificationCoordinatorJob
    queue: maintenance
    schedule: every 5 minutes
  schedule_verse_notifications:
    class: VerseNotificationCoordinatorJob
    queue: maintenance
    schedule: every 15 minutes
  resolve_scripture_circle_votes:
    class: ScriptureCircles::Moderations::ResolveDueJob
    queue: maintenance
    schedule: every 5 minutes
  clean_notification_records:
    class: NotificationsCleanupJob
    queue: maintenance
    schedule: every day at 3am
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
